options:
  docker: true

definitions:
  steps:
    - step: &docker-build-push
        name: Build docker image and push
        image: google/cloud-sdk:alpine
        script:
          #- export ARTIFACT_ID = fence
          - export IMAGE_NAME=eu.gcr.io/${GCLOUD_PROJECT}/fence:${BITBUCKET_COMMIT}
          #Login to Google repo
          - echo $GCLOUD_API_KEYFILE | base64 -d > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          - gcloud config set project ${GCLOUD_PROJECT}
          - cat ./gcloud-api-key.json | docker login -u _json_key --password-stdin https://eu.gcr.io
          #Building and pushing image to the Google repo
          - docker build -t ${IMAGE_NAME} .
          - docker push ${IMAGE_NAME}
    - step: &deploytoec2
        name: deploy and install on uat
        image: atlassian/pipelines-awscli
        script:
          -
          - export TAG=${BITBUCKET_COMMIT}
          - wget -qO- https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz | tar xvz
          - chmod +x ./linux-amd64/helm && mv ./linux-amd64/helm /usr/local/bin/helm
          - wget https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
          - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
          - aws eks update-kubeconfig --name datlatest-eks-eu --region eu-west-1
          - helm -f helm/values.yaml upgrade ${DEPLOYMENT} helm -n ${NAMESPACE} --set image.tag=${TAG} --set env.PG_URI=${PG_URI} --set env.PG_USR=${PG_USR} --set env.PG_PWD=${PG_PWD}
pipelines:
  branches:
    origin/release/awsireland:
      - step: *docker-build-push
      - step: *deploytoec2
