# syntax=docker/dockerfile:1
FROM openjdk:17-alpine3.14 as base
WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
COPY src ./src


FROM base as test
# for better performance use RUN below . use RUN to test during build itself rather than during run
RUN ["./mvnw", "test"]

FROM base as build
RUN ./mvnw package

# make sure you have a running postgres before you call the below target
FROM base as uat
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=uat" ]
#ENTRYPOINT ["tail", "-f", "/dev/null"]

FROM openjdk:17.0.1-jdk-slim as uat-slim
EXPOSE 11000
COPY --from=build /app/target/fencekc-*.jar /fencekc-0.1.0-SNAPSHOT.jar
CMD ["java", "-Djava.security.egd=file:/dev/./urandom" , "-jar" , "/fencekc-0.1.0-SNAPSHOT.jar"]
