server:
  port: 11000

spring:
  datasource:
    platform: h2
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName:

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: fuser
      password: fpwd
    realmImportFile: realm-fencedev.json
