spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: ${PG_URI:jdbc:postgresql://localhost:5555/fencekc}
    username: ${PG_USR:fenceuser}
    password: ${PG_PWD:fencepwd}
    driverClassName: org.postgresql.Driver
keycloak:
  server:
    adminUser:
      username: fuser
      password: fpwd
    realmImportFile: realm-fencedev.json

server:
  port: '11000'